# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include themes.yaml
  extra_module_url:
    - /local/sidebarHandler.js?v={{ now().timestamp() | int }}
    - /local/dashHandler.js?v={{ now().timestamp() | int }}
    - /local/calendarHandler.js?v={{ now().timestamp() | int }}


lovelace:
  resources:
    - url: /hacsfiles/lovelace-fullcalendar-card/lovelace-fullcalendar-card.js
      type: module
    - url: /hacsfiles/gallery-card/gallery-card.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/bootstrap-grid-card/bootstrap-grid-card.js
      type: module
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/digital-clock/digital-clock.js
      type: module

  dashboards:
    family-dashboard:
      mode: yaml
      filename: skylight_dashboard_wrapper.yaml
      title: Panogu Family
      icon: mdi:home-heart
      show_in_sidebar: true
      require_admin: false

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
template: !include template.yaml
