# Loads default set of integrations. Do not remove.
default_config:

# Ensure card-mod loads as a frontend module (needed for sticky sidebar stylings)
frontend:
  themes: !include themes.yaml

# Expose dashboard as YAML
lovelace:
  dashboards:
    family-dashboard:
      mode: yaml
      title: Family
      icon: mdi:home-heart
      show_in_sidebar: true
      filename: dashboards/family_dashboard.yaml

automation: !include automations.yaml
script: !include scripts.yaml
template: !include template.yaml

input_number: !include input_number.yaml
input_select: !include input_select.yaml
