
default_config:

frontend:
  themes: !include themes.yaml
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

lovelace:
  dashboards:
    family-dashboard:
      mode: yaml
      title: Family
      icon: mdi:home-heart
      show_in_sidebar: true
      filename: dashboards/family_dashboard.yaml

automation: !include automations.yaml
script: !include scripts.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
template: !include template.yaml
sensor: !include sensor.yaml
input_text: !include input_text.yaml