# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include themes.yaml
  extra_module_url:
    - /local/sidebarHandler.js?v={{ now().timestamp() | int }}
    - /local/dashHandler.js?v={{ now().timestamp() | int }}
    - /local/calendarHandler.js?v={{ now().timestamp() | int }}

lovelace:
  resources:
    - url: https://fonts.googleapis.com/css2?family=Nunito:wght@400;600;700&family=Quicksand:wght@400;600&display=swap
      type: css
  dashboards:
    family-dashboard:
      mode: yaml
      filename: skylight_dashboard_wrapper.yaml
      title: Panogu Family
      icon: mdi:home-heart
      show_in_sidebar: true
      require_admin: false

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
template: !include template.yaml
