default_config:

# frontend:
  # themes: !include themes.yaml

lovelace:
  mode: yaml
  resources:
    - url: /local/family-board/family-dashboard-controller.js
      type: module
    - url: /local/family-board/family-board.js
      type: module


automation: !include automations.yaml
script: !include scripts.yaml
template: !include template.yaml
sensor: !include sensor.yaml

# TODO
# click a chip and if it is calendar it only shows their items
# click a chip and if it is chores it only shows their chores
# heading: move the time to the left next to the name
# style the shit out of full calendar now I have it
# find something to do todoist like full calendar
# obviously we want to make the buttons nicer on the calendar
#
#
#
