# Loads default set of integrations. Do not remove.
default_config:

# Ensure card-mod loads as a frontend module (needed for sticky sidebar stylings)
frontend:
  extra_module_url:
    - /hacsfiles/lovelace-card-mod/card-mod.js

# Expose dashboard as YAML
lovelace:
  dashboards:
    family-dashboard:
      mode: yaml
      title: Family
      icon: mdi:home-heart
      show_in_sidebar: true
      filename: dashboards/family_dashboard.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_select: !include input_select.yaml
input_text: !include input_text.yaml
input_datetime: !include input_datetime.yaml
input_boolean: !include input_boolean.yaml
template: !include template.yaml
