
default_config:

frontend:
  themes: !include themes.yaml

lovelace:
  mode: yaml
  resources:
    - url: /hacsfiles/lovelace-card-mod/card-mod.js
      type: module
    - url: /hacsfiles/button-card/button-card.js
      type: module
    - url: /hacsfiles/lovelace-layout-card/layout-card.js
      type: module
    - url: /hacsfiles/week-planner-card/week-planner-card.js
      type: module
  dashboards:
    family-dashboard:
      mode: yaml
      title: Family
      icon: mdi:home-heart
      show_in_sidebar: true
      filename: dashboards/family_dashboard.yaml

automation: !include automations.yaml
script: !include scripts.yaml
input_select: !include input_select.yaml
input_number: !include input_number.yaml
template: !include template.yaml
sensor: !include sensor.yaml
input_text: !include input_text.yaml